#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Agentforce test-lab setup"

# ── Prerequisite: toolchain ────────────────────────────────────────────────
if ! command -v sf >/dev/null 2>&1; then
  warn "The Salesforce CLI (sf) is not installed."
  say "Install it, then re-run this wizard:"
  say "  npm install -g @salesforce/cli"
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  warn "python3 is required (used to parse CLI output). Install it and re-run."
  exit 1
fi

# Helper: in-place sed that works on both GNU and BSD (macOS).
_edit() { local f="$1"; if sed --version >/dev/null 2>&1; then sed -i "$2" "$f"; else sed -i '' "$2" "$f"; fi; }

# Helper: JSON helper that tolerates control characters in CLI output.
_jsonval() {
  python3 -c "import json,sys,re; d=json.loads(re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]','',sys.stdin.read())); print(d.get('result',{}).get(sys.argv[1]))" "$1"
}

# ── Stage 1: log in to the org ─────────────────────────────────────────────
stage "Log in to the org"
say "We'll authenticate to your Salesforce org. A browser window will open."
ask ORG_ALIAS "Org alias (later commands use this):"
ask ORG_URL "Org URL [https://login.salesforce.com]"
ORG_URL="${ORG_URL:-https://login.salesforce.com}"
say "Running the CLI web login now. Complete it in the browser, then return."
open_url "${ORG_URL%%/}"
sf org login web --alias "$ORG_ALIAS" --instance-url "$ORG_URL" --set-default
pause "Logged in? (browser should say authorized — then press Enter)"
SF_USERNAME=$(sf org display --target-org "$ORG_ALIAS" --json | _jsonval "username")
note "Detected username: $SF_USERNAME"
write_env ORG_ALIAS "$ORG_ALIAS"
write_env ORG_URL "$ORG_URL"
write_env SF_USERNAME "$SF_USERNAME"

# ── Stage 2: verify it's a sandbox ─────────────────────────────────────────
stage "Verify sandbox"
say "Security tests must target a sandbox. Checking org type."
SANDBOX_JSON=$(sf data query -q "SELECT IsSandbox, Name, OrganizationType FROM Organization LIMIT 1" -o "$ORG_ALIAS" --json || true)
IS_SANDBOX=$(printf '%s' "$SANDBOX_JSON" | python3 -c "import json,sys,re; d=json.loads(re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]','',sys.stdin.read())); r=d.get('result',{}).get('records',[{}])[0]; print(r.get('IsSandbox', False))" 2>/dev/null || echo false)
if [ "$IS_SANDBOX" = "true" ]; then
  note "✓ Sandbox confirmed."
else
  warn "This does NOT look like a sandbox. Agentforce security testing is sandbox-only."
  confirm "Continue with a production org anyway?" || { say "Stopping — re-run with a sandbox."; exit 1; }
fi

# ── Stage 3: scaffold the agent project ────────────────────────────────────
stage "Scaffold the agent project"
say "Creating an SFDX project from the CLI's bundled 'agent' template"
say "(Local_Info_Agent sample: weather, events, resort hours)."
ask AGENT_PROJECT "Project directory name [AgentLab]"
AGENT_PROJECT="${AGENT_PROJECT:-AgentLab}"
if [ -d "$AGENT_PROJECT" ]; then
  warn "Directory '$AGENT_PROJECT' already exists — skipping scaffold."
else
  sf template generate project --name "$AGENT_PROJECT" --template agent --default-package-dir force-app
fi
write_env AGENT_PROJECT "$AGENT_PROJECT"
AGENT_BUNDLE="Local_Info_Agent"

# ── Stage 4: set the default agent user ────────────────────────────────────
stage "Set the default agent user"
say "The template ships with a placeholder default_agent_user; replace it"
say "with the username from stage 1 so the agent compiles."
AGENT_FILE=$(find "$AGENT_PROJECT" -name "*.agent" -path "*aiAuthoringBundles*" | head -1)
AGENT_FILE="${AGENT_FILE:-$AGENT_PROJECT/force-app/main/default/aiAuthoringBundles/$AGENT_BUNDLE/$AGENT_BUNDLE.agent}"
note "File: $AGENT_FILE"
if [ -f "$AGENT_FILE" ]; then
  CURRENT=$(grep -oE 'default_agent_user: ".*?"' "$AGENT_FILE" | head -1 | sed 's/.*: "//; s/"$//')
  note "Current placeholder: ${CURRENT:-<none>}"
  confirm "Replace it with '$SF_USERNAME'?" && {
    _edit "$AGENT_FILE" "s|default_agent_user: \"[^\"]*\"|default_agent_user: \"$SF_USERNAME\"|"
    grep -q "default_agent_user: \"$SF_USERNAME\"" "$AGENT_FILE" && note "✓ Updated." || warn "Auto-edit failed — fix the line manually."
  }
else
  warn "Agent file not found; edit default_agent_user manually after scaffolding."
fi

# ── Stage 5: deploy metadata to the org (confirm gate) ─────────────────────
stage "Deploy metadata"
say "Deploying the agent bundle, flow, Apex, prompt template, and permission"
say "sets so live action targets (apex://, flow://, prompt://) exist."
confirm "Push these metadata components to '$ORG_ALIAS' now?" || { say "Skipped — live actions won't resolve until deployed."; pause; skip_deploy=1; }
if [ -z "${skip_deploy:-}" ]; then
  ( cd "$AGENT_PROJECT" && sf project deploy start --target-org "$ORG_ALIAS" -w 5 )
fi

# ── Stage 6: smoke test the agent ──────────────────────────────────────────
stage "Smoke test (simulated actions)"
say "Running one preview session against the local .agent file, with"
say "actions simulated so nothing real executes."
( cd "$AGENT_PROJECT" &&
  SESSION_ID=$(sf agent preview start --json --authoring-bundle "$AGENT_BUNDLE" --simulate-actions --target-org "$ORG_ALIAS" 2>/dev/null | _jsonval "sessionId") &&
  echo "  Preview session: $SESSION_ID" &&
  sf agent preview send --json --session-id "$SESSION_ID" --authoring-bundle "$AGENT_BUNDLE" --utterance "What's the weather at the resort today?" --target-org "$ORG_ALIAS" 2>/dev/null | python3 -c "
import json,sys,re
d=json.loads(re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]','',sys.stdin.read()))
m=d.get('result',{}).get('messages',[])
print('  Agent reply: '+((m[-1].get('message','') if m else '')[:200]))
" &&
  sf agent preview end --json --session-id "$SESSION_ID" --authoring-bundle "$AGENT_BUNDLE" --target-org "$ORG_ALIAS" >/dev/null 2>&1 ) \
  || warn "Smoke test failed — see the trace at .sfdx/agents/ for diagnosis."

finish
